version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  # Install the haxe chocolatey package (https://chocolatey.org/packages/haxe)
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  # Setup haxelib
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  # Install test dependencies
  - cinst php -y
  # Download and setup a standalone flash player debugger
  - haxe flash/install.hxml
  # Install project dependencies
  - haxelib install hxcpp  > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hxjava > log.txt || type log.txt && cmd /C exit 1
  - haxelib install hxcs   > log.txt || type log.txt && cmd /C exit 1
  - haxelib dev hscript .
  - haxelib list

build: off

test_script:
  - pushd script &&
    haxe build.hxml &&
    popd
  - haxe build-interp.hxml
  - haxe build-neko.hxml         && neko bin\Test.n
  - haxe build-js.hxml           && node bin\Test.js
  - haxe build-java.hxml         && java -jar bin\Test.jar
  - haxe build-cs.hxml           && bin\bin\Test.exe
  - haxe build-cpp.hxml          && bin\Test.exe
  - haxe build-flash.hxml -D fdb && haxe flash\run.hxml bin\Test.swf
  - haxe build-php.hxml          && C:\tools\php\php.exe bin\index.php
  - haxe build-python.hxml       && C:\Python34-x64\python.exe bin\Test.py